
services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:${DB_VERSION:-8.4}
    container_name: ${PROJECT_NAME}_mysql
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-!ChangeMe!}
      MYSQL_DATABASE: ${DB_DATABASE:-app}
      MYSQL_USER: ${DB_USER:-app}
      MYSQL_PASSWORD: ${DB_PASSWORD:-!ChangeMe!}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - ${PROJECT_NAME}_web
    volumes:
      - database_data:/var/lib/mysql:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${PROJECT_NAME}_phpmyadmin
    platform: linux/amd64
    environment:
      PMA_HOST: ${PROJECT_NAME}_mysql
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    networks:
      - ${PROJECT_NAME}_web
    ports:
      - "8080:80"
    depends_on:
      - database

  php:
    build:
      context: .
    container_name: ${PROJECT_NAME}_php
    volumes:
      - .:/var/www/html
    networks:
      - ${PROJECT_NAME}_web

  nginx:
    image: nginx:latest
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - .:/var/www/html
    depends_on:
      - php
    networks:
      - ${PROJECT_NAME}_web

networks:
  portfolio_web:
      driver: bridge

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
